"""Generate native_tests/lstm_golden.h from torch.nn.LSTM (single layer, unidirectional,
batch_first=False). Run in the ExecuTorch export venv:
  /home/corey/workspace/executorch/.venv/bin/python tools/gen_lstm_golden.py
"""
import torch

T, B, I, H = 4, 2, 3, 5
torch.manual_seed(0)
lstm = torch.nn.LSTM(I, H, num_layers=1, bias=True, batch_first=False, bidirectional=False).eval()
x = torch.randn(T, B, I)
h0 = torch.randn(B, H)
c0 = torch.randn(B, H)
with torch.no_grad():
    out, (hn, cn) = lstm(x, (h0.unsqueeze(0), c0.unsqueeze(0)))

def arr(name, t):
    flat = ", ".join(f"{v:.8e}f" for v in t.flatten().tolist())
    return f"constexpr float {name}[] = {{{flat}}};"

lines = [
    "// GENERATED by tools/gen_lstm_golden.py — do not edit by hand.",
    "#pragma once",
    "namespace lstm_golden {",
    f"constexpr int T = {T}, B = {B}, I = {I}, H = {H};",
    arr("input", x),
    arr("h0", h0), arr("c0", c0),
    arr("w_ih", lstm.weight_ih_l0), arr("w_hh", lstm.weight_hh_l0),
    arr("b_ih", lstm.bias_ih_l0), arr("b_hh", lstm.bias_hh_l0),
    arr("output", out), arr("hn", hn.squeeze(0)), arr("cn", cn.squeeze(0)),
    "}  // namespace lstm_golden",
]
open("native_tests/lstm_golden.h", "w").write("\n".join(lines) + "\n")
print("wrote native_tests/lstm_golden.h")
