# Generated by executorch-runtime-dist release v1.3.1-10. Do not edit by hand.
#
# Select a variant with the helper below; FetchContent only the pair it
# returns, so unused variants download nothing:
#   et_runtime_dist_url("${ET_RUNTIME_VARIANT}" "${platform}" url sha)
#
# The ET_RUNTIME_OPENVINO_* vars are optional (contract C10): they are absent from releases
# that published no bundle, and the bundle exists for ET_RUNTIME_OPENVINO_PLATFORM only.
set(ET_RUNTIME_VERSION "1.3.1-10")
set(ET_RUNTIME_ET_VERSION "1.3.1")

set(ET_RUNTIME_URL_bare_linux-aarch64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-10/executorch-runtime-1.3.1-bare-linux-aarch64.tar.gz")
set(ET_RUNTIME_SHA256_bare_linux-aarch64 "cbc6536074786f5cc3381a5700a31b314715caaf58aca79e1e930e3c8a45be8c")

set(ET_RUNTIME_URL_devtools_linux-aarch64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-10/executorch-runtime-1.3.1-devtools-linux-aarch64.tar.gz")
set(ET_RUNTIME_SHA256_devtools_linux-aarch64 "2dca28131e516765198a99783a3f1aad174173c415753ecc6a4f05853a75e1b6")

set(ET_RUNTIME_URL_logging_linux-aarch64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-10/executorch-runtime-1.3.1-logging-linux-aarch64.tar.gz")
set(ET_RUNTIME_SHA256_logging_linux-aarch64 "87e487b3487fd6e3c1dda600dcee514feee729462949badfab1c6dd2b5db4d4b")

set(ET_RUNTIME_URL_bare_linux-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-10/executorch-runtime-1.3.1-bare-linux-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_bare_linux-x86_64 "8a952644b4fef53774933919069aa532ab22a086f744e8d381b9e4ac4ddef6b5")

set(ET_RUNTIME_URL_devtools_linux-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-10/executorch-runtime-1.3.1-devtools-linux-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_devtools_linux-x86_64 "d3066fff2834f71f684ec59a34f5a2aa608dbe94094415b296d138fba677fc8b")

set(ET_RUNTIME_URL_logging_linux-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-10/executorch-runtime-1.3.1-logging-linux-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_logging_linux-x86_64 "a20eaff9c391ce45f87e3195a00581e1bb6a0885a47649f18d360dfe5cf97630")

set(ET_RUNTIME_URL_logging_windows-x86_64
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-10/executorch-runtime-1.3.1-logging-windows-x86_64.tar.gz")
set(ET_RUNTIME_SHA256_logging_windows-x86_64 "cca54f241397d7e21276da9f3af0e03702eb64336c5a8e4ad7ef177f02e105ad")

set(ET_RUNTIME_URL_logging_windows-x86_64-static
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-10/executorch-runtime-1.3.1-logging-windows-x86_64-static.tar.gz")
set(ET_RUNTIME_SHA256_logging_windows-x86_64-static "f5f8036c035dea722a14928ca2894c8c583d93deaa0f6b9a42d3b625a79532fc")

function(et_runtime_dist_url variant platform out_url out_sha)
  set(_k "${variant}_${platform}")
  if(NOT DEFINED ET_RUNTIME_URL_${_k})
    message(FATAL_ERROR
      "executorch-runtime-dist: no artifact for variant='${variant}' platform='${platform}'")
  endif()
  set(${out_url} "${ET_RUNTIME_URL_${_k}}" PARENT_SCOPE)
  set(${out_sha} "${ET_RUNTIME_SHA256_${_k}}" PARENT_SCOPE)
endfunction()

set(ET_RUNTIME_OPENVINO_VERSION "2025.4.1")
set(ET_RUNTIME_OPENVINO_PLATFORM "linux-x86_64")
set(ET_RUNTIME_OPENVINO_URL
  "https://github.com/measly-java-learning/executorch-runtime-dist/releases/download/v1.3.1-10/openvino-runtime-2025.4.1-linux-x86_64.tar.gz")
set(ET_RUNTIME_OPENVINO_SHA256 "066084d23d1e70395929f840368c6ce1a2e43f5969989d9f5bd595265d10ce7b")

